### ISSUE TITLE
Don't use Conda

### ISSUE THREAD

**Issue by Keno** [JuliaMath/FFTW.jl#118]
Installing FFTW.jl installs Conda, apparently to be able to test MKL on CI. This should be unnecessary. We have a MKL in Yggradsil, so we should be able to just install it: https://github.com/JuliaPackaging/Yggdrasil/blob/master/M/MKL/build_tarballs.jl.

**Comment by ChrisRackauckas** [comment]
If it's just for testing, why is it not a just a test dependency?

**Comment by stevengj** [comment]
It's not just a test dependency — if you configure FFTW.jl with `JULIA_FFTW_PROVIDER=MKL`, and you don't have an MKL build of Julia, then it installs MKL for you with Conda.

Now that it is on Yggdrasil, I agree that we can just install it from there.

Once the whole "jll" mechanism lands, however, will this mean that we have to add a dependency on both FFTW.jll and MKL.jll, so that everyone has to install both binaries even if they are only using one?  I'm still pining for optional dependencies in Pkg.

**Comment by ianshmean** [comment]
Some progress over in #127 but looks like we need `IntelOpenMP_jll` too

**Comment by ianshmean** [comment]
#127 has been merged, so master no longer uses Conda. Ready for a release?
