### ISSUE TITLE
Wrong results when doing irfft -> rfft

### ISSUE THREAD

**Issue by appleparan** [JuliaMath/FFTW.jl#29]
`FFTW.jl`failed some FFT test that I made. I wanted to figure out why it is and tested with fortran and FFTW. 

I used `Julia` v0.6.0 and `FFTW.jl`  v0.0.4. All other packages are up-to-date (using `Pkg.update()`)

At first, I generated random complex array even with imaginary part. However, FFTW also failed. I asked stackoverflow and got an [answer](
https://stackoverflow.com/questions/45571840/why-combination-of-backward-fftc2r-and-forward-real-input-fft-r2c-to-one-com) Therefore, I changed array generation with zero imaginary part. I found FFTW (fortran ver.) works.

Here is my test code.
 
```
using Base.Test
using FFTW

nx = 5; ny = 8
a = rand(nx, ny) + im * zeros(nx, ny)
@test norm(FFTW.rfft(FFTW.irfft(a, (nx - 1) * 2)) - a) < 1e-8
```

It didn't passed because norm is large as 10^-1 order.
I know it's not normal to `irfft` to `rfft`, but when I printed results and compared the results I found this seems a **bug**. However, `rfft` to `irfft` from another real array is working well.

```
@show a
@show FFTW.rfft(FFTW.irfft(a, (nx - 1) * 2))
```

This shows **first row** and **last row** (except first column and last column) are different with original array `a`.

```
a = Complex{Float64}[
0.731823+0.0im 0.0914679+0.0im 0.421424+0.0im 0.66566+0.0im 0.676793+0.0im 0.91561+0.0im 0.167977+0.0im 0.81144+0.0im;
0.955786+0.0im 0.988594+0.0im 0.946422+0.0im 0.469863+0.0im 0.567468+0.0im 0.410604+0.0im 0.0876826+0.0im 0.350643+0.0im;
0.675414+0.0im 0.376511+0.0im 0.411776+0.0im 0.634354+0.0im 0.324661+0.0im 0.456795+0.0im 0.648942+0.0im 0.938804+0.0im;
0.879751+0.0im 0.801969+0.0im 0.209773+0.0im 0.229292+0.0im 0.47708+0.0im 0.488061+0.0im 0.553131+0.0im 0.459141+0.0im;
0.0991666+0.0im 0.743879+0.0im 0.751298+0.0im 0.96974+0.0im 0.407805+0.0im 0.726425+0.0im 0.766682+0.0im 0.0755481+0.0im]

FFTW.rfft(FFTW.irfft(a, (nx - 1) * 2)) = Complex{Float64}[
0.731823+0.0im 0.451454+0.0im 0.294701+0.0im 0.790635+0.0im 0.676793+0.0im 0.790635+0.0im 0.294701+0.0im 0.451454+0.0im;
0.955786+0.0im 0.988594+0.0im 0.946422+0.0im 0.469863+0.0im 0.567468+0.0im 0.410604+0.0im 0.0876826+0.0im 0.350643+0.0im;
0.675414+0.0im 0.376511+0.0im 0.411776+0.0im 0.634354+0.0im 0.324661+0.0im 0.456795+0.0im 0.648942+0.0im 0.938804+0.0im;
0.879751+0.0im 0.801969+0.0im 0.209773+0.0im 0.229292+0.0im 0.47708+0.0im 0.488061+0.0im 0.553131+0.0im 0.459141+0.0im;
0.0991666+0.0im 0.409713+0.0im 0.75899+0.0im 0.848083+0.0im 0.407805+0.0im 0.848083+0.0im 0.75899+0.0im 0.409713+0.0im]
```

I also tested with `python 3.6.2` and recent version of `numpy`   . I used same value generated from `Julia`, but python has passed the test. I also tested randomly generated complex array, this is  also passed.

```
import numpy.fft as fft
import numpy as np
import numpy.linalg as lin
import numpy.random as random

def run():
    nx = 5
    ny = 8

    #a = [[0.0091934+0.0j, 0.887909+0.0j, 0.022417+0.0j, 0.377631+0.0j, 0.57725+0.0j, 0.759539+0.0j, 0.497938+0.0j, 0.50837+0.0j], [0.36253+0.0j, 0.250405+0.0j, 0.335141+0.0j, 0.836328+0.0j, 0.517139+0.0j, 0.976069+0.0j, 0.0158171+0.0j, 0.919675+0.0j], [0.830197+0.0j, 0.731117+0.0j, 0.738942+0.0j, 0.729338+0.0j, 0.00759557+0.0j, 0.159997+0.0j, 0.848967+0.0j, 0.277697+0.0j], [0.536876+0.0j, 0.199403+0.0j, 0.281549+0.0j, 0.136321+0.0j, 0.240842+0.0j, 0.58003+0.0j, 0.294667+0.0j, 0.330748+0.0j], [0.276797+0.0j, 0.0450511+0.0j, 0.990411+0.0j, 0.174055+0.0j, 0.218758+0.0j, 0.940231+0.0j, 0.158844+0.0j, 0.12785+0.0j]]
    a = random.rand(nx, ny) + np.zeros((nx, ny)) * 1j

    print(a)
    b = fft.rfft(fft.irfft(a))
    print(b)

    print(lin.norm(a - b))

if __name__ == '__main__':
    run()
```

However, 1D case even with not setting imaginary part as zero, `ifft` -> `rfft` works.

```
# 1D real FFT Test
nx = 16

a = rand(nx)
#@test norm(FFTW.irfft(FFTW.rfft(a), nx) - a) < 1e-8
@test norm(FFTW.irfft(FFTW.rfft(a), nx) - a) < 1e-12

a = rand(nx) + im * zeros(nx)
@test norm(FFTW.rfft(FFTW.irfft(a, (length(a) - 1) * 2)) - a) < 1e-12
```

**Comment by appleparan** [comment]
Confusing to add this issue to FFTW.jl because `irfft` and `rfft` are belong to `AbstractFFTs.jl`. However, `irfft` normalized version of `brfft` and their tests are at `FFTW.jl`

One more thing. Is this related to #25 ?

**Comment by ararslan** [comment]
> Is this related to #25 ?

Not if you're on Julia 0.6. On Julia 0.6, this package just reuses the Base bindings to the FFTW library (indeed, this package is not necessary at all on 0.6). Do you get the same thing if you omit `using FFTW`?

**Comment by appleparan** [comment]
Yes.

**Comment by appleparan** [comment]
1. No problem with 1D case. (seems this is due to https://github.com/JuliaMath/FFTW.jl/blob/3e7d50b2152c0ecd0a8b3d7e4f3bcad5e65ebfde/src/fft.jl#L673)

2. rfft ->irfft doesn't have the problem.

3. Now I'm inspecting https://github.com/JuliaMath/FFTW.jl/blob/3e7d50b2152c0ecd0a8b3d7e4f3bcad5e65ebfde/src/fft.jl#L504 this part.

**Comment by stevengj** [comment]
It's not a bug.  The problem is that `irfft` is the inverse of `rfft`: the inputs to `irfft` must be equal to the output of `rfft` of some data.  The key point is that when you compute the FFT of real-input data, the complex output has certain conjugate symmetries.  Your inputs to `irfft` must have these symmetries, or it will give unexpected results.  See http://fftw.org/doc/Multi_002ddimensional-Transforms.html

This is not the case in your example, because you are just giving random complex numbers to `irfft`.  This doesn't have the symmetry that (~half of) a conjugate-symmetric array would have.

**Comment by stevengj** [comment]
(Another way of putting it: what linear transformation do you think `irfft` is computing, which takes complex inputs and produces real outputs?)

**Comment by appleparan** [comment]
@stevengj So, storing half dimension of last dimension (first dimension in FORTRAN) is not enough? I thought that's why FFTW store full dimension of array due to Hermitian symmetry.

**Comment by stevengj** [comment]
@applebaum, the problem is that the `rfft` output format stores a *little more than half* of the complex output.  This means that it still contains some redundancies.

e.g. for a 1d FFT of an (even) length N, the `rfft` output (`N` real inputs) has `N/2+1` complex outputs, corresponding to `2(N/2+1) = N+2` real outputs: 2 extra numbers.   The redundancy here (the 2 extra numbers) stems from the fact that the first and last complex outputs are always purely real, so that their 2 imaginary parts are zero.

In principle, there are ways to pack the outputs of an `N`-element `rfft` into exactly `N` real outputs (see e.g. the "halfcomplex" format in FFTW or the [DHT](https://en.wikipedia.org/wiki/Discrete_Hartley_transform)).   Unfortunately, none of them generalize well to higher dimensions: they are all more difficult to compute and/or require annoying post-processing to get the actual Fourier amplitudes.

**Comment by applebaum** [comment]
@stevengj ok
