### ISSUE TITLE
How to avoid the performance loss of rfft function after using fft function？

### ISSUE THREAD

**Issue by liushang0322** [JuliaMath/FFTW.jl#305]
```julia
using FFTW
using Random
a = rand(100000000)
@time rfft(a);
```
```dataframe
0.307048 seconds (228 allocations: 762.957 MiB, 7.69% gc time)
```
But when I use fft once first and then use the above code

```julia
using FFTW
using Random
a = rand(100000000)
fft(a)
@time rfft(a);
```

```dataframe
2.986037 seconds (228 allocations: 762.957 MiB, 1.63% gc time)
```

Performance is about ten times worse，How to avoid the performance loss of rfft function after using fft function？

**Comment by stevengj** [comment]
I can't replicate your timings on my machine.  I suspect that you're just being fooled by the unreliability of `@time` (in particular, you want to discount the time from the first time you call a function, since not only is some compilation involved, but FFTW also creates a "plan" object that can potentially be re-used.  Better to use `@btime` from the [BenchmarkTools.jl package](https://github.com/JuliaCI/BenchmarkTools.jl) to get reliable timing measurements.

However, if you care about performance, you should be using `plan_rfft` anyway to create a "plan" (saved algorithm and data tables) for the FFT and then re-use it.
