### ISSUE TITLE
FFTW is GPL. Mention in licence file?!

### ISSUE THREAD

**Issue by PallHaraldsson** [JuliaMath/FFTW.jl#39]
and probably also README?

I think "GPL applies to dependency" should be prominently added to license file. Before MIT.

Only seeing "MIT license" is misleading, and users may want to know about GPL or get in legal trouble otherwise(?).

I think this also applies to DSP.jl (but not AbstractFFTs.jl).

**Comment by ararslan** [comment]
None of the code in this package is _derived_ from FFTW. Libraries which call into external, GPL-licensed code do not themselves need to be licensed under GPL. That's why this code was not licensed under GPL while it was in Base. Another example of this is [Rmath.jl](https://github.com/JuliaStats/Rmath.jl), which calls R's GPL-licensed math library but is itself licensed under MIT. 

A mention of the GPL does not belong in the license file, as the fact that FFTW is GPL is irrelevant to the code here. However, a mention in the readme could be worthwhile, as we do with Rmath.

**Comment by ararslan** [comment]
> I think this also applies to DSP.jl

It does not.
