### ISSUE TITLE
Spurious *incremental compilation may be broken* messages on Julia 0.6

### ISSUE THREAD

**Issue by cormullion** [JuliaMath/FFTW.jl#46]
![dc2fd854-a538-4e35-8e5b-3bdcb8cf10f1](https://user-images.githubusercontent.com/52289/31812980-a364ee02-b57c-11e7-8255-710b09e99f66.jpeg)

I noticed it on [this](http://juliagraphics.github.io/Luxor.jl/latest/moreexamples.html) page of some docs.

I think this is probably only a problem on Travis (can’t get it locally) but I’m just curious...

**Comment by ararslan** [comment]
It's a problem that occurs on Julia 0.6 when a package that has precompilation enabled depends on FFTW. On 0.6, this package doesn't define a module at all; it simply refers to `Base.FFTW`. This is to avoid errors from name conflicts. The downside is then that precompiled packages look for the cache file for FFTW and can't find it.

I assume in the case of your documentation that doc deployment happens on 0.6. To avoid it in the docs, you could deploy from 0.7, if you support 0.7, or turn off doc testing and use `julia-repl` rather than `jldoctest` for example blocks.

Something we may want to consider (though I'm not certain it would work) is to generate an empty cache file on 0.6 so that there's something there for package precompilation to find. That will require more thought and experimentation though.

**Comment by cormullion** [comment]
@ararslan OK, cool. Yes, v0.6 works, and I think it's going to be a few months before all packages work on 0.7. (Cairo, Images, Juno, etc...). It's only a minor problem anyway, and it will go away next year. Feel  free to close this issue if you want... :)

**Comment by ararslan** [comment]
Nah, I'll leave it open until I can figure something out that will actually give users a decent experience on 0.6.

**Comment by ararslan** [comment]
This package now requires Julia 0.7 at a minimum and there's nothing we can do for the 0.6 situation, so I'm just going to close this. Thanks for the report!
