### ISSUE TITLE
Remove 0.6 Versions?

### ISSUE THREAD

**Issue by tknopp** [JuliaMath/FFTW.jl#53]
This package should not not be installable in Julia 0.6, see https://github.com/JuliaImages/ImageCore.jl/issues/56

Is there a way to remove the old versions that allows installation under 0.6? If not please close. But in the future, code that is split of base should not be installable in a stable version of Julia.

**Comment by ararslan** [comment]
It's intentionally installable on 0.6 so that package authors can target both 0.6 and 0.7. The warning emitted on 0.6 is very unfortunate but is harmless. If we really want to prevent people from installing it on 0.6, we'll have to change the bounds in METADATA, which are considered immutable for all but the most extreme circumstances.
