### ISSUE TITLE
Segmentation fault on Mac

### ISSUE THREAD

**Issue by juliohm** [JuliaMath/FFTW.jl#63]
My Travis build on Mac is failing consistently, apparently due to FFTW. Could you please share some thoughts on what might be happening and how I can fix it? https://travis-ci.org/juliohm/ImageQuilting.jl/jobs/346038516#L595-L614

**Comment by ararslan** [comment]
I don't think this is related to FFTW but I could be wrong. The warnings you're seeing from FFTW are expected on 0.6 since there's no cache file for the package, it just uses the Base bindings. Something you could do to test locally would be to remove FFTW from your REQUIRE file and rerun the tests on 0.6. If they still segfault, try running it with LLDB (or GDB, if you prefer).

**Comment by juliohm** [comment]
Thank you @ararslan , it seems like it is coming from Hwloc.jl? I opened an issue there instead. I don't know if something changed about Hwloc on Mac, but I am just calling a single function `num_physical_cores()`.
