### ISSUE TITLE
How can I transform of 2D FFTW fro image?

### ISSUE THREAD

**Issue by bemoregt** [JuliaMath/FFTW.jl#92]

**Comment by stevengj** [comment]
FFTW is a low-level C library that takes arrays of floating-point values as input.  You need to convert your image to this format in order to use it.

In general, for high-level tasks like image processing, it is probably easier to use a high-level library.  For example, http://scikit-image.org/docs/0.3/api/scikits.image.transform.html#scikits.image.transform.fft

**Comment by stevengj** [comment]
See also https://juliaimages.org/latest/arrays_colors.html for how to convert Julia images (from the Images.jl package) to numeric types, and also https://juliaimages.org/latest/conversions_views.html#Color-separations:-views-for-converting-between-numbers-and-colors-1

**Comment by bemoregt** [comment]
HI, @stevengj 

Thanks a lot.

I will try this.
